// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIHdOnan0ktZ1NCMMu3MwtBALExOVG-gs',
    appId: '1:914346774165:web:43a01a9447f04ad3b1959c',
    messagingSenderId: '914346774165',
    projectId: 'easy-buyer-9bcbc',
    authDomain: 'easy-buyer-9bcbc.firebaseapp.com',
    storageBucket: 'easy-buyer-9bcbc.appspot.com',
    measurementId: 'G-9162W2F9E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnXcx7SM-WAbywNAtTIYwbM4PdMUPiVYI',
    appId: '1:914346774165:android:7eddc2e0129cbf47b1959c',
    messagingSenderId: '914346774165',
    projectId: 'easy-buyer-9bcbc',
    storageBucket: 'easy-buyer-9bcbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuiiYxO8TkhiKjtJF-8nWprJLtcfrnI0U',
    appId: '1:914346774165:ios:a562786fc63afdc8b1959c',
    messagingSenderId: '914346774165',
    projectId: 'easy-buyer-9bcbc',
    storageBucket: 'easy-buyer-9bcbc.appspot.com',
    iosBundleId: 'com.example.busticss1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuiiYxO8TkhiKjtJF-8nWprJLtcfrnI0U',
    appId: '1:914346774165:ios:ed5f5d5b34a7509eb1959c',
    messagingSenderId: '914346774165',
    projectId: 'easy-buyer-9bcbc',
    storageBucket: 'easy-buyer-9bcbc.appspot.com',
    iosBundleId: 'com.example.busticss1.RunnerTests',
  );
}
